[build]
  publish = "public"
  # If you use PostCSS/Tailwind, let npm run first; otherwise you can just use "hugo --gc --minify"
  command = "hugo --gc --minify"

[build.environment]
  # Use the Hugo (extended) version you use locally: run `hugo version` to check
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  # If your theme is a git submodule:
  GIT_SUBMODULE_STRATEGY = "recursive"